In [50]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix,f1_score, accuracy_score
from sklearn.neighbors import KNeighborsClassifier

In [11]:
data = pd.read_csv("diabetes.csv")

In [12]:
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [14]:
# Replace zero values to mean value

zero = ["Glucose","BloodPressure","SkinThickness","BMI","Insulin"]

for column in zero:
    data[column] = data[column].replace(0, np.NaN)
    mean = int(data[column].mean(skipna= True))
    data[column] = data[column].replace(np.NaN, mean)

In [15]:
data["BloodPressure"]

0      72.0
1      66.0
2      64.0
3      66.0
4      40.0
       ... 
763    76.0
764    70.0
765    72.0
766    60.0
767    70.0
Name: BloodPressure, Length: 768, dtype: float64

In [16]:
# Split the dataset

X = data.iloc[:,0:8]
y = data.iloc[:,8]

X_train , X_test, y_train, y_test = train_test_split(X,y, random_state=0, test_size=0.2)

In [17]:
# Feature Scaling

scaling_X = StandardScaler()
X_train = scaling_X.fit_transform(X_train)
X_test = scaling_X.transform(X_test)

In [18]:
X_train

array([[ 0.90832902,  0.93641795,  0.44764174, ...,  0.36863635,
         0.67740401,  1.69955804],
       [ 0.03644676, -0.81630913, -1.05200558, ..., -0.63294341,
        -0.07049698, -0.96569189],
       [-1.12606292,  1.43247278,  1.44740662, ...,  2.81535261,
        -0.11855487, -0.88240283],
       ...,
       [ 0.03644676, -0.91552009, -0.63543688, ..., -1.13373329,
        -0.95656442, -1.04898095],
       [ 2.0708387 , -1.21315299,  0.11438678, ..., -0.36108605,
        -0.50001442,  0.11706589],
       [ 0.32707418,  0.47343344,  0.7808967 , ..., -0.08922869,
         0.52121586,  2.94889395]])

In [20]:
import math
math.sqrt(len(y_test))

12.409673645990857

In [21]:
# Define the model
model = KNeighborsClassifier(n_neighbors=11,p =2, metric="euclidean")

In [22]:
model.fit(X_train,y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=11)

In [23]:
predict = model.predict(X_test)

In [24]:
predict

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [26]:
#Evaluate the model
conf = confusion_matrix(y_test,predict)
print(conf)

[[94 13]
 [15 32]]


In [27]:
print(f1_score(y_test, predict))

0.6956521739130436


In [28]:
print(accuracy_score(y_test, predict))

0.8181818181818182


In [40]:
#Predicting
def scaller(predict):
    scalling = StandardScaler()
    predict =scalling.fit_transform(predict)
    return predict

In [45]:
print(model.predict(scaller([[10,139,80,19,68,27.1,1.441,57]])))

[0]


In [48]:
print(model.predict(scaller([[5,166,72,19,175,25.8,0.587,51]])))

[0]
