In [15]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

In [5]:
data = pd.read_csv("wine.csv")

In [8]:
data = pd.DataFrame(data)

In [9]:
data

Class   Alcohol  Malic acid       Ash  Alcalinity of ash  Magnesium  \
0        1  0.571053    0.205534  0.417112           0.030928   0.326087   
1        2  0.547368    0.053360  0.181818           0.226804   0.086957   
2        3  0.636842    0.584980  0.663102           0.639175   0.445652   
3        1  0.807895    0.280632  0.502674           0.381443   0.380435   
4        2  0.444737    0.199605  0.491979           0.613402   0.152174   
..     ...       ...         ...       ...                ...        ...   
173      1  0.765789    0.195652  0.486631           0.350515   0.413043   
174      2  0.365789    0.171937  0.443850           0.613402   0.413043   
175      1  0.736842    0.179842  0.663102           0.340206   0.260870   
176      1  0.665789    0.191700  0.508021           0.288660   0.510870   
177      2  0.207895    0.144269  0.336898           0.525773   0.173913   

     Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0         0.575862    0.510549              0.245283         0.274448   
1         0.689655    0.599156              0.245283         0.589905   
2         0.248276    0.122363              0.566038         0.331230   
3         0.679310    0.628692              0.169811         0.621451   
4         0.137931    0.299578              0.660377         0.384858   
..             ...         ...                   ...              ...   
173       0.655172    0.675105              0.358491         0.526814   
174       0.351724    0.369198              0.396226         0.378549   
175       0.506897    0.559072              0.169811         0.593060   
176       0.748276    0.622363              0.396226         0.608833   
177       0.344828    0.265823              0.320755         0.353312   

     Color intensity       Hue  OD280/OD315 of diluted wines   Proline  
0           0.264505  0.463415                      0.780220  0.550642  
1           0.343003  0.520325                      0.699634  0.159772  
2           0.802048  0.300813                      0.106227  0.297432  
3           0.381399  0.626016                      0.695971  0.878745  
4           0.172355  0.325203                      0.421245  0.149786  
..               ...       ...                           ...       ...  
173         0.650171  0.520325                      0.670330  0.700428  
174         0.066553  0.471545                      0.619048  0.047789  
175         0.368601  0.617886                      0.769231  0.703994  
176         0.413823  0.382114                      0.772894  0.368759  
177         0.057167  0.382114                      0.754579  0.154779  

[178 rows x 14 columns]

In [10]:
# to separate the data set as a X and y
X = data.drop("Class", axis=1)

In [11]:
X

Alcohol  Malic acid       Ash  Alcalinity of ash  Magnesium  \
0    0.571053    0.205534  0.417112           0.030928   0.326087   
1    0.547368    0.053360  0.181818           0.226804   0.086957   
2    0.636842    0.584980  0.663102           0.639175   0.445652   
3    0.807895    0.280632  0.502674           0.381443   0.380435   
4    0.444737    0.199605  0.491979           0.613402   0.152174   
..        ...         ...       ...                ...        ...   
173  0.765789    0.195652  0.486631           0.350515   0.413043   
174  0.365789    0.171937  0.443850           0.613402   0.413043   
175  0.736842    0.179842  0.663102           0.340206   0.260870   
176  0.665789    0.191700  0.508021           0.288660   0.510870   
177  0.207895    0.144269  0.336898           0.525773   0.173913   

     Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0         0.575862    0.510549              0.245283         0.274448   
1         0.689655    0.599156              0.245283         0.589905   
2         0.248276    0.122363              0.566038         0.331230   
3         0.679310    0.628692              0.169811         0.621451   
4         0.137931    0.299578              0.660377         0.384858   
..             ...         ...                   ...              ...   
173       0.655172    0.675105              0.358491         0.526814   
174       0.351724    0.369198              0.396226         0.378549   
175       0.506897    0.559072              0.169811         0.593060   
176       0.748276    0.622363              0.396226         0.608833   
177       0.344828    0.265823              0.320755         0.353312   

     Color intensity       Hue  OD280/OD315 of diluted wines   Proline  
0           0.264505  0.463415                      0.780220  0.550642  
1           0.343003  0.520325                      0.699634  0.159772  
2           0.802048  0.300813                      0.106227  0.297432  
3           0.381399  0.626016                      0.695971  0.878745  
4           0.172355  0.325203                      0.421245  0.149786  
..               ...       ...                           ...       ...  
173         0.650171  0.520325                      0.670330  0.700428  
174         0.066553  0.471545                      0.619048  0.047789  
175         0.368601  0.617886                      0.769231  0.703994  
176         0.413823  0.382114                      0.772894  0.368759  
177         0.057167  0.382114                      0.754579  0.154779  

[178 rows x 13 columns]

In [12]:
y = data.Class

In [16]:
# split the dataset 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle= True, stratify= y)

In [18]:
model = SVC()

In [28]:
#determine the parameter values
param_grid = {"C":(1,10,100,1000),"gamma":(0.1,0.01,0.001,0.0001)}

In [29]:
# create the Grid Search model
grid_search = GridSearchCV(model, param_grid, cv=10, verbose=10,return_train_score=False)

In [30]:
grid_search.fit(X_train, y_train)

Fitting 10 folds for each of 16 candidates, totalling 160 fits
[CV 1/10; 1/16] START C=1, gamma=0.1............................................
[CV 1/10; 1/16] END .............C=1, gamma=0.1;, score=1.000 total time=   0.0s
[CV 2/10; 1/16] START C=1, gamma=0.1............................................
[CV 2/10; 1/16] END .............C=1, gamma=0.1;, score=1.000 total time=   0.0s
[CV 3/10; 1/16] START C=1, gamma=0.1............................................
[CV 3/10; 1/16] END .............C=1, gamma=0.1;, score=0.929 total time=   0.0s
[CV 4/10; 1/16] START C=1, gamma=0.1............................................
[CV 4/10; 1/16] END .............C=1, gamma=0.1;, score=0.929 total time=   0.0s
[CV 5/10; 1/16] START C=1, gamma=0.1............................................
[CV 5/10; 1/16] END .............C=1, gamma=0.1;, score=1.000 total time=   0.0s
[CV 6/10; 1/16] START C=1, gamma=0.1............................................
[CV 6/10; 1/16] END .............C=1, gamma=0.

[CV 3/10; 6/16] END ...........C=10, gamma=0.01;, score=0.929 total time=   0.0s
[CV 4/10; 6/16] START C=10, gamma=0.01..........................................
[CV 4/10; 6/16] END ...........C=10, gamma=0.01;, score=0.857 total time=   0.0s
[CV 5/10; 6/16] START C=10, gamma=0.01..........................................
[CV 5/10; 6/16] END ...........C=10, gamma=0.01;, score=1.000 total time=   0.0s
[CV 6/10; 6/16] START C=10, gamma=0.01..........................................
[CV 6/10; 6/16] END ...........C=10, gamma=0.01;, score=1.000 total time=   0.0s
[CV 7/10; 6/16] START C=10, gamma=0.01..........................................
[CV 7/10; 6/16] END ...........C=10, gamma=0.01;, score=0.929 total time=   0.0s
[CV 8/10; 6/16] START C=10, gamma=0.01..........................................
[CV 8/10; 6/16] END ...........C=10, gamma=0.01;, score=1.000 total time=   0.0s
[CV 9/10; 6/16] START C=10, gamma=0.01..........................................
[CV 9/10; 6/16] END ........

[CV 8/10; 11/16] END ........C=100, gamma=0.001;, score=1.000 total time=   0.0s
[CV 9/10; 11/16] START C=100, gamma=0.001.......................................
[CV 9/10; 11/16] END ........C=100, gamma=0.001;, score=1.000 total time=   0.0s
[CV 10/10; 11/16] START C=100, gamma=0.001......................................
[CV 10/10; 11/16] END .......C=100, gamma=0.001;, score=1.000 total time=   0.0s
[CV 1/10; 12/16] START C=100, gamma=0.0001......................................
[CV 1/10; 12/16] END .......C=100, gamma=0.0001;, score=0.400 total time=   0.0s
[CV 2/10; 12/16] START C=100, gamma=0.0001......................................
[CV 2/10; 12/16] END .......C=100, gamma=0.0001;, score=0.400 total time=   0.0s
[CV 3/10; 12/16] START C=100, gamma=0.0001......................................
[CV 3/10; 12/16] END .......C=100, gamma=0.0001;, score=0.429 total time=   0.0s
[CV 4/10; 12/16] START C=100, gamma=0.0001......................................
[CV 4/10; 12/16] END .......

GridSearchCV(cv=10, estimator=SVC(C=1, gamma=0.1),
             param_grid={'C': (1, 10, 100, 1000),
                         'gamma': (0.1, 0.01, 0.001, 0.0001)},
             verbose=10)

In [31]:
# Check the best parameter
grid_search.best_params_

{'C': 10, 'gamma': 0.1}

In [32]:
# to place the best parameters and fit
model = SVC(C=1, gamma=0.1).fit(X_train, y_train)

In [33]:
model.score(X_test,y_test)

1.0

In [35]:
predict = model.predict(X_test)

In [37]:
#Control the confusion matrix and classification Report
print("Confusion Matrix: ")
print(confusion_matrix(y_test, predict))
print()
print("Classifiction Report :")
print(classification_report(y_test, predict))

Confusion Matrix: 
[[12  0  0]
 [ 0 14  0]
 [ 0  0 10]]

Classifiction Report :
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        12
           2       1.00      1.00      1.00        14
           3       1.00      1.00      1.00        10

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36

